version: '3'
services:
  mongo:
    image: mongo:3.6.23
    ports:
      - 27017:27017
    volumes:
      - ./tmp/db:/data/db  

  api:
    image: demoreset-api:latest
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    links:
      - mongo:27017
